apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: app
  labels:
    app: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: <registry>.container-registry.ovh.net/library/backend:latest # TODO: update to your env
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresql-<<database>>.database.cloud.ovh.net:20184/defaultdb?sslmode=require # TODO: update to your env
            - name: SPRING_DATASOURCE_USERNAME
              value: avnadmin
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: PASSWORD
            - name: version
              value: "6"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
