apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ovh-workshop-1
spec:
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
