apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ovh-workshop-1
spec:
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
