traefik:
  deployment:
    replicas: 1
    revisionHistoryLimit: 1

  globalArguments: []

  ports:
    web:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  providers:
    kubernetesCRD:
      allowCrossNamespace: true

  additionalArguments:
    - '--providers.kubernetesingress.ingressendpoint.publishedservice=traefik/traefik'

  resources:
    requests:
      cpu: '100m'
      memory: '50Mi'
    limits:
      cpu: '300m'
      memory: '150Mi'

  autoscaling:
    enabled: false
